### ISSUE TITLE
Créer un petit pst test

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-mails#36]
### EPIC

https://github.com/SocialGouv/archifiltre-private/issues/1

### AFTER

#

### Contexte

Dans le cadre des développements d'Archimail, nous avons besoin de pouvoir tester sur un petit pst dont on a créé le contenu dont on maitrise complètement le contenu.

### Définition du(des) problème(s)

Les pst que nous avons sont très gros et le contenu n'est pas maitrisable.

### Solution

ETQ testeur d'Archimail
JVP tester l'extraction sur un petit pst comportant:
- des éléments reçus
- des éléments envoyés
- des éléments d'agenda
- des dossiers avec des mails classés 
AD vérifier l'extraction et l'exhaustivité 

### Les tests e2e doivent-ils passer ?

- [ ] e2e

### Valeur Business

BV:L

**Comment by lsagetlethias** [comment]
liamihcra@outlook.fr

**Comment by lsagetlethias** [comment]
## Contenu :
### Mail :
**Boîte de réception** :
- (Confirmation réponse "Deadline Archimail") - reçu "02/11/2021 à 14h39"
- Réponse fil "Au sujet des tests sur Archimail", from "lilian.sagetlethias@beta.gouv.fr", reçu le "02/11/2021 à 14h39", text : "Ok d'accord"

**Éléments envoyés** :
- titre : "Au sujet des tests sur Archimail", to : "lilian.sagetlethias@beta.gouv.fr", date : "02/11/2021 à 14h26", text : "Lorem ipsum ..."
- (invitation "Deadline Archimail"), to : "lilian.sagetlethias@beta.gouv.fr", date : "02/11/2021 à 14h30"

**Éléments supprimés** :
- titre "Bonjour ici", from "lilian.sagetlethias@beta.gouv.fr", data : "02/11/2021 à 14h50", text : "Comme planifié, voici le mail présent"

### Agenda :
**Créé** :
- 1er Décembre 2021 / Titre : "Deadline Archimail" / Toute la journée / Invités : "lilian.sagetlethias@beta.gouv.fr"

### Contact :
**Dossier "Contacts"** :
- prénom : "Lilian", nom : "Saget-Lethias", mail "lilian.sagetlethias@beta.gouv.fr", entreprise : "Beta gouv / DENUM", note : "ping lilian"

**Dossier perso "Spéciaux"** :
- prénom : "Lilian Bis", nom : "SL", mail : "lilian.sagetlethias+bis@beta.gouv.fr"

**Comment by lsagetlethias** [comment]
[liamihcra.olm.zip](https://github.com/SocialGouv/archimail/files/7461788/liamihcra.olm.zip)
(to convert in PST)

**Comment by lsagetlethias** [comment]
[liamihcra.pst.zip](https://github.com/SocialGouv/archimail/files/7466696/liamihcra.pst.zip)

**Comment by lsagetlethias** [comment]
# v2
## Ajouts
### Mail :
**Dossier "Boîte de réception"** :
- from: "lilian.sagetlethias@gmail.com" ; to: "liamihcra@outlook.fr", "lilian.sagetlethias@beta.gouv.fr"; title: "2 destinataires" ; 10/11/2021 12:04 ; - marqué comme Tâche
- from: "lilian.sagetlethias@gmail.com" ; to: "lilian.sagetlethias@gmail.com" ; cc: "liamihcra@outlook.fr" ; title: "Liamihcra en CC" ; 10/11/2021 12:06" - NON LU
- from: "lilian.sagetlethias@gmail.com" ; to: "lilian.sagetlethias@beta.gouv.fr" ; bcc: "liamihcra@outlook.fr" ; title: "Liamihcra en BCC / CCI" ; 10/11/2021 12:07" - NON LU
- from: "postmaster@outlook.com" ; to: "liamihcra@outlook.fr" ; title: "Non remis : Venant de Limicrah, 0 dest, 2 cc, 1 bcc" ; 10/11/2021 12:19
- from: "Lilian Saget-Lethias <lilian.sagetlethias@beta.gouv.fr>" ; to: "Archimail Test <liamihcra@outlook.fr>" ; cc: "Lilian Saget-Lethias <lilian.sagetlethias@beta.gouv.fr>; lilian.sagetlethias@gmail.com" ; title: "Re: Venant de Limicrah, 0 dest, 2 cc, 1 bcc" : 10/11/2021 12:19
- from: "Lilian Saget-Lethias <lilian.sagetlethias@gmail.com>" ; to: "Archimail Test <liamihcra@outlook.fr>" ; cc: "Lilian Saget-Lethias <lilian.sagetlethias@beta.gouv.fr>" ; title: "Re: Venant de Limicrah, 0 dest, 2 cc, 1 bcc" ; 10/11/2021 12:20

**Dossier "Éléments envoyés"** :
- to: empty ; cc: "Lilian Saget-Lethias <lilian.sagetlethias@beta.gouv.fr>; lilian.sagetlethias@gmail.com" ; cci: "Lilian Bis SL <lilian.sagetlethias+bis@beta.gouv.fr>" ; title: "Venant de Limicrah, 0 dest, 2 cc, 1 bcc" ; 10/11/2021 12:18 ; (avec mise en page et emojis)
- to: "lilian.sagetlethias@beta.gouv.fr" ; title: "Message à caractère informatif" ; "10/11/2021 12:31" (Importance haute)
- to: "lilian.sagetlethias@beta.gouv.fr" ; title: "Message à caractère désinformatif" ; "10/11/2021 12:32" (Importance faible)

**Dossier "Courrier indésirable"** :
- from: "Lilian Saget-Lethias <lilian.sagetlethias@gmail.com>"; to: empty ; cci: "liamihcra@outlook.fr" ; title: "3 personnes en BCC / CCI" ; 10/11/2021 12:07

[liamihcraV2.pst.zip](https://github.com/SocialGouv/archimail/files/7512341/liamihcraV2.pst.zip)
