### ISSUE TITLE
Reprendre le nom des éléments parent à côté de la visualisation

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-mails#81]
### EPIC

https://github.com/SocialGouv/archifiltre-private/issues/3

### AFTER

https://github.com/SocialGouv/archimail/issues/29

### Contexte

Quand on dépose un pst, on affiche sous forme de Bubbles l'ensemble des mails par domaine puis par correspondant puis par année puis l'ensemble des mails concerné.

### Définition du(des) problème(s)

On ne sait pas à quoi correspond la Bubble contenante qui englobe toutes les autres.

### Solution

ETQ utilisateur d'Archifiltre-Mails
JVP comprendre le sens de la Bubble principale en affichant son titre à côté de la Bubble
AD mieux comprendre la navigation

### Les tests e2e doivent-ils passer ?

- [ ] e2e

### Valeur Business

BV:L

**Comment by lsagetlethias** [comment]
Duplicate of #29
